<?php
include '../Controller/ProductC.php';
include '../model/product.php';

$error = "";

// Create an instance of the controller
$produitC = new ProductC();

if (
    isset($_POST["productName"]) &&
    isset($_POST["quantity"]) &&
    isset($_POST["unitPrice"])
) {
    if (
        !empty($_POST['productName']) &&
        !empty($_POST["quantity"]) &&
        !empty($_POST["unitPrice"])
    ) {
        // Create a new product object
        $produit = new Produit(
            null, // idProduct is null as it is auto-generated by the database
            $_POST['productName'],
            $_POST['quantity'],
            $_POST['unitPrice']
        );

        // Add the product using the controller
        $produitC->addProduct($produit);
        
        // Redirect or show a success message
        header('Location: index.php');  // Redirect to product listing page (example)
    } else {
        $error = "Missing information";
    }
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
    <title>ALPHA Web Admin Panel</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f6f7;
            margin: 0;
        }

        .side-menu ul {
            list-style: none;
            padding: 0;
        }

        .side-menu ul li {
            margin: 20px 0;
            font-size: 16px;
        }

        .side-menu ul li img {
            width: 20px;
            margin-right: 10px;
        }

        .side-menu ul li a {
            text-decoration: none;
            color: white;
            font-weight: bold;
            display: flex;
            align-items: center;
            padding: 8px;
            border-radius: 5px;
        }

        .side-menu ul li a:hover {
            background-color: rgb(180, 185, 41);
            transition: background-color 0.3s;
        }

        .container {
            width: 80%;
            padding: 20px;
            background-color: rgb(240, 241, 236);
            min-height: 100vh;
            color: rgb(68, 80, 44);
        }

        .form-container {
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
            max-width: 800px;
            margin: 0 auto;
        }

        h1 {
            text-align: center;
            color: #2c3e50;
        }

        #error {
            color: red;
            text-align: center;
            font-size: 16px;
        }

        form table {
            width: 100%;
            margin-top: 20px;
        }

        form table td {
            padding: 10px;
            font-size: 16px;
        }

        form input[type="text"],
        form input[type="number"],
        form input[type="submit"],
        form input[type="reset"] {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #ddd;
            border-radius: 5px;
            box-sizing: border-box;
        }

        form input[type="submit"],
        form input[type="reset"] {
            width: 48%;
            background-color: #2980b9;
            color: white;
            border: none;
            cursor: pointer;
            font-weight: bold;
        }

        form input[type="submit"]:hover,
        form input[type="reset"]:hover {
            background-color: #3498db;
            transition: background-color 0.3s;
        }

        #errorProductName,
        #errorQuantity,
        #errorUnitPrice {
            color: red;
            font-size: 14px;
        }

        .emoji {
            font-size: 18px;
            margin-right: 5px;
        }

        .btn-primary {
            background-color: #2980b9;
            color: white;
            padding: 10px 20px;
            border-radius: 5px;
            font-weight: bold;
            text-align: center;
            text-decoration: none;
        }

        .btn-primary:hover {
            background-color: #3498db;
            transition: background-color 0.3s;
        }

        .btn-danger {
            background-color: #e74c3c;
            color: white;
            padding: 8px 15px;
            border-radius: 5px;
            text-decoration: none;
        }

        .btn-danger:hover {
            background-color: #c0392b;
            transition: background-color 0.3s;
        }

        .btn-update {
            background-color: #f39c12;
            color: white;
            padding: 8px 15px;
            border-radius: 5px;
            text-decoration: none;
        }

        .btn-update:hover {
            background-color: #e67e22;
            transition: background-color 0.3s;
        }

        .btn-view {
            background-color: #16a085;
            color: white;
            padding: 8px 15px;
            border-radius: 5px;
            text-decoration: none;
        }

        .btn-view:hover {
            background-color: #1abc9c;
            transition: background-color 0.3s;
        }

        .form-container table td input {
            margin-bottom: 10px;
        }
    </style>
</head>

<body>
    <!-- Sidebar -->
    <div class="side-menu">
        <div class="brand-name">
            <img src="images/logos.png" alt="">&nbsp;<h2>FIRMA-TAK</h2>
        </div>
        <ul>
            <a href="#"><li><img src="images/dashboard (2).png" alt="">&nbsp; <span>Dashboard</span> </li></a>
            <a href="index.php"><li><img src="images/reading-book (1).png" alt="">&nbsp;<span>Products</span> </li></a>
        </ul>
    </div>

    <!-- Main Content -->
    <div class="container">
        <!-- Form Section -->
        <div class="form-container">
            <h1>Add Product <span class="emoji">➕</span></h1>
            <div id="error">
                <?php echo $error; ?>
            </div>
            <form action="" method="POST" id="productForm">
                <table>
                    <tr>
                        <td><label for="productName">Product Name <span class="emoji">🛒</span>:</label></td>
                        <td>
                            <input type="text" id="productName" name="productName" />
                            <span id="errorProductName" style="color: red"></span>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="quantity">Quantity <span class="emoji">🔢</span>:</label></td>
                        <td>
                            <input type="number" id="quantity" name="quantity" />
                            <span id="errorQuantity" style="color: red"></span>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="unitPrice">Unit Price <span class="emoji">💲</span>:</label></td>
                        <td>
                            <input type="number" step="0.01" id="unitPrice" name="unitPrice" />
                            <span id="errorUnitPrice" style="color: red"></span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="submit" value="Save 📝">
                        </td>
                        <td>
                            <input type="reset" value="Reset 🔄">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>

    <script>
        // Function to validate form inputs
        function validateForm(event) {
            // Reset error messages
            document.getElementById("errorProductName").innerText = "";
            document.getElementById("errorQuantity").innerText = "";
            document.getElementById("errorUnitPrice").innerText = "";

            let isValid = true;

            // Get values from the form
            const productName = document.getElementById("productName").value.trim();
            const quantity = document.getElementById("quantity").value.trim();
            const unitPrice = document.getElementById("unitPrice").value.trim();

            // Validate Product Name
            if (productName === "") {
                document.getElementById("errorProductName").innerText = "Product name is required.";
                isValid = false;
            }

            // Validate Quantity
            if (quantity === "") {
                document.getElementById("errorQuantity").innerText = "Quantity is required.";
                isValid = false;
            } else if (quantity <= 0) {
                document.getElementById("errorQuantity").innerText = "Quantity must be a positive number.";
                isValid = false;
            }

            // Validate Unit Price
            if (unitPrice === "") {
                document.getElementById("errorUnitPrice").innerText = "Unit price is required.";
                isValid = false;
            } else if (unitPrice <= 0) {
                document.getElementById("errorUnitPrice").innerText = "Unit price must be a positive number.";
                isValid = false;
            }

            // If invalid, prevent form submission
            if (!isValid) {
                event.preventDefault();
            }
        }

        // Attach the validation function to the form submission
        document.getElementById("productForm").addEventListener("submit", validateForm);
    </script>
</body>

</html>
